language: node_js
node_js:
  - 6
  - 7
services:
  - redis-server
env:
  - CXX=g++-4.8
before_install:
  - "npm config set spin false"
  - "npm install -g mocha"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
